MaheshDoiphode/hacktoberfest-LeetCode-2022

Java/2. Add_Two_Numbers.java

Medium level problem solved in Java

2nd Problem of the LeetCode i.e., Add Two Numbers

---

C++/11.Container With Most Water.cpp

This question is from leetcode: https://leetcode.com/problems/container-with-most-water/

Added question 11.Container With Most Water.cpp

---

Java/9. Palindrome_Number.java

Adding 9. Palindrome_Number.java

Adding 9. Palindrome_Number.java

---

Java/14.Longest_Common_Prefix.java

Solution 13

---

Java/f.java

Hacktoberfest contribution by @ashutosh7i

44.Wildcard_Matching.java

---

Java/25.Rotate_Image.java

added a new solution of rotate image from leet code and added the time complexity in comments

Added a new question about rotate image 

---

C++/84. Largest_Rectangle_in_Histogram.cpp

Added solution for LC Problem : 84. Largest Rectangle in Histogram
Problem Link:
https://leetcode.com/problems/largest-rectangle-in-histogram/

Added solution for LC Problem : 84. Largest Rectangle in Histogram

---

C++/19. Remove Nth Node From End of List
C++/3. Longest Substring Without Repeating Characters

Added Solution to the problem
Problem Link : https://leetcode.com/problems/longest-substring-without-repeating-characters/

A3. Longest Substring Without Repeating Characters

---

CONTRIBUTING.md
Java/1816.Truncate_Sentence.java

Solution to the program 1816 of Leetcode using split() method.

Leetcode Program 1816: Truncate Sentence

---

C++/Leetcode problem 295. Find Median from Data Stream.cpp

This is the solution to the following problem of leetcode: https://leetcode.com/problems/find-median-from-data-stream/

Leetcode problem 295. Find Median from Data Stream.cpp

---

C++/301. Remove Invalid Parentheses.cpp

Leetcode problem 301. Remove Invalid Parentheses
Given a string s that contains parentheses and letters, remove the minimum number of invalid parentheses to make the input string valid.
Return all the possible results. You may return the answer in any order.
Example 1:
Input: s = "()())()"
Output: ["(())()","()()()"]
Example 2:
Input: s = "(a)())()"
Output: ["(a())()","(a)()()"]

Leetcode Question 301. Remove Invalid Parentheses.cpp

---

C++/1512. Number of Good Pairs.cpp
C++/2236. Root Equals Sum of Children.cpp
CONTRIBUTING.md

- 1512. Number of Good Pairs
- 2236. Root Equals Sum of Children

Two Problems Added in C++

---

C++/18.4sum.cpp

Added one of the most standard questions and frequently asked in interviews, 4Sum question.

Added 18.4sum.cpp

---

Java/88. Merge Sorted Array

Create 88. Merge Sorted Array

---

Java/42.Trapping_Rain_Water.java

This is the solution of program number 42 on Leetcode

Trapping_Rain_Water

---

3sum-closest.cpp
C++/17.LetterCombOfPhoneNumbers.cpp

Hacktoberfest-2022 3SumClosest.cpp

---

Java/9.Palindrome-number.java

Solution of problem 9 of Leetcode without converting the number to String.

9. Palindrome Number

---

Python/104. Maximum Depth of Binary Tree.py
Python/111. Minimum Depth of Binary Tree.py
Python/144. Binary Tree Preorder Traversal.py
Python/145. Binary Tree Postorder Traversal.py
Python/94. Binary Tree Inorder Traversal.py

I have added solutions to five problems related to the Binary Search Tree in Python language.
-Binary Tree Inorder Traversal
-Binary Tree Preorder Traversal
-Binary Tree Postorder Traversal
-Maximum depth of a binary tree
-Minimum depth of a binary tree

Question related to BST added(in Python)

---

Java/283.Move_Zeroes.java

This is the solution of program number 283 on Leetcode

283.Move_Zeroes

---

CONTRIBUTING.md
Java/1828.Query-number-of-points-in-circle

Solution to problem 1828 on Leetcode in Java.

1828. Queries on Number of Points Inside a Circle

---

C++/1502. Can Make Arithmetic Progression From Sequence.cpp
C++/1828. Queries on Number of Points Inside a Circle.cpp
C++/1920. Build Array from Permutation.cpp
C++/34. Find First and Last Position of Element in Sorted Array.cpp
C++/35. Search Insert Position.cpp
C++/51. N-Queens.cpp
CONTRIBUTING.md

Hey ! , its my 2nd pull request for hacktofest2022 , by adding 6 leetcode problems

adding 6 problems , leetcode ,Easy||Medium||Hard

---

416. Partition Equal Subset Sum.py

2 approaches for 416. Partition equal subset sum question on LeetCode. Explained using comments wherever necessary.

Create 416. Partition Equal Subset Sum.py

---

Java/2235.Add_Two_Integers.java

2235.Add Two Integers

---

188. Best Time to Buy and Sell Stock IV.cpp

Explained with comments solution for hard rated 188. Best time to buy and sell stocks variation problem. Used recursion and memoization.

Create 188. Best Time to Buy and Sell Stock IV.cpp

---

Java/1823.Find_the_Winner_of_the_Circular_Game.java

This is the solution of program number 1823 on Leetcode

Find_the_Winner_of_the_Circular_Game

---

CONTRIBUTING.md
CONTRIBUTORS.md

Addressing the issue of `CONTRIBUTING.md and CONTRIBUTORS.md should be separated` by myself, I have created a separate file for the contribution guidelines.
Please customize the contribution guidelines as per your norms.
The structure of CONTRIBUTORS has been improved as well.

CONTRIBUTORS and CONTRIBUTING Segregated

---

Python/97. Interleaving String.py

Given strings s1, s2, and s3, this code helps find whether s3 is formed by an interleaving of s1 and s2.

Create 97. Interleaving String.py

---

C++/66.Plus_One.cpp

Added Code for LeetCode 66. Plus One Question

66. Plus One (C++)
